services:
  postgres:
    image: postgres:15-alpine
    container_name: appointment-postgres
    environment:
      POSTGRES_DB: appointmentdb
      POSTGRES_USER: appointment_user
      POSTGRES_PASSWORD: appointment_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: appointment-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: appointment-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: appointment_user
      RABBITMQ_DEFAULT_PASS: appointment_pass
    ports:
      - "5672:5672"
      - "15672:15672"

  appointment-app: # Add this later after Dockerfile step!
    build: .
    container_name: appointment-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appointmentdb
      SPRING_DATASOURCE_USERNAME: appointment_user
      SPRING_DATASOURCE_PASSWORD: appointment_pass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: appointment_user
      SPRING_RABBITMQ_PASSWORD: appointment_pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq

volumes:
  postgres_data:
